### ISSUE TITLE
hmm.fit_HMM(perc_std_expl) didn't work in run model 

### ISSUE THREAD

**Issue by Zouhour03** [pipette/Electricity-load-prediction#2]

**Comment by Zouhour03** [comment]
![image](https://user-images.githubusercontent.com/17108132/39538709-f40bb02a-4e3d-11e8-83b6-a3d5cf74f4d2.png)
I have this error please help me

**Comment by Zouhour03** [comment]
with open('Trained_model.pkl','wb') as f:
    pk.dump(fhmm,f)
i have an empty file 0 octets

**Comment by AmanYdv20** [comment]
Can you please provide me the dataset,I am not able to find it.

**Comment by Christian97C** [comment]
Can you please provide me the dataset,I am not able to find it, please

**Comment by pipette** [comment]
@Christian97C see the latest commit, link to the dataset has been fixed. For other issues please keep in mind that this project was done in 2 weeks more than 4 years ago as a graduation project for Data Science bootcamp. It is in no way complete or even a mature piece of code. I've also not been coming back to it in the past four years - I am sure there are other great resources for load disaggregation.

**Comment by Christian97C** [comment]
Thank you very much for the information, I am just doing a thesis topic for
the graduation at the University on the disaggregation of the load of the
industrial sector in Ecuador and I wanted to test these algorithms with the
data they mention, and then proceed to test with data from the industries
in my city.
